name = "MooshRegistry"
uuid = "d3d129ad-3d09-48e0-a834-ead9fc7ab1fc"
repo = "git@github.com:ps-pat/Moosh-Registry.git"
description = "Registry for anything Moosh related."

[packages]
778192d3-ef18-4ce5-814b-6356444560f1 = { name = "Simulations", path = "S/Simulations" }
99b31415-443e-43a2-8bf4-ca532bb4a161 = { name = "Moosh", path = "M/Moosh" }
